### ISSUE TITLE
Rest API Milestone

### ISSUE THREAD

**Issue by prionkor** [prionkor/yith-woocommerce-wishlist-rest-api#1]
See [https://github.com/yithemes/yith-woocommerce-wishlist/issues/9](https://github.com/yithemes/yith-woocommerce-wishlist/issues/9
)

Continue of the discussion from [WP Support Forum](https://wordpress.org/support/topic/feature-request-rest-api-support/#post-13843910)

I am going to for this project and start the development. If you have any preferred guidelines on how you structure your code let me know. I am using a [pattern like this](https://github.com/prionkor/codeware-wp-plugin-scaffold).

Namespace
--------
`/yith/wishlist/v1`

Proposed Endpoint for (CRUD)
--------

**GET `{url}/wishlists`**
Users with credentials will be returned with an array of wishlists object.

**POST `{url}/wishlists`**

Add product/s to wishlist endpoint. Users with credentials will be returned with a wishlists object created from the POST data. if no wishlist id was provided a new wishlist is created otherwise the object with the given id returned.

**Params:**

`wishlistId`: id of the wishlist
`productIds`: an array of product ids. for a single product add send one element array.
`userId` (optional): In the case of client credentials or API key, admin user auth send userId. For a user auth userId isn't required because userId will be gathered from authentication. Defaults to the current user. (needs discussion) 

**DELETE `{url}/wishlists/{id}`**

Clears the wishlist data.

**DELETE `{url}/wishlists/{id}/product/{product_id}`**

Removes the given product id from wishlist id

**Comment by prionkor** [comment]
Tasks

- [x] Get list of wishlist
- [x] Get single wishlist
- [ ] Create Wishlist
- [ ] Update Wishlist
- [x] Add product to wishlist
- [x] Remove product from wishlist
- [ ] Delete wishlist 
- [ ] Clean wishlist (delete all products form wishlists
- [ ] Create Documentations

**Comment by harishksoft** [comment]
![image](https://user-images.githubusercontent.com/27539252/131214392-1b34054e-b812-49e4-a4f6-563231efc3a1.png)
getting error like this
